//
// Created by Samuel on 05/02/2024.
//

#ifndef INC_2024_I_AV_SW_CONFIG_HPP
#define INC_2024_I_AV_SW_CONFIG_HPP

#define SENS_ACCEL_AMNT 3
#define SENS_ACCEL_RATE 100

#define SENS_GYRO_AMNT 3
#define SENS_GYRO_RATE 100

#define SENS_MAG_AMNT 3
#define SENS_MAG_RATE 20

#define SENS_BARO_AMNT 3
#define SENS_BARO_RATE 100

#define SENS_GNSS_AMNT 1
#define SENS_GNSS_RATE 10

#endif //INC_2024_I_AV_SW_CONFIG_HPP
